source 'https://rubygems.org'

gem 'actionmailer', '4.1.6'
gem 'actionpack', '4.1.6'
gem 'actionview', '4.1.6'
gem 'activemodel', '4.1.6'
gem 'activerecord', '4.1.6'
gem 'activesupport', '4.1.6'
gem 'bundler', '>= 1.3.0'
gem 'railties', '4.1.6'
gem 'sprockets-rails', '~> 2.0'
