# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50174ba5b83b8c6867c785cd29f76c8198acc81880f72bff6ad82586d883fb1969e8afc62d8e1a58d81e5975589f78d7e620de16f8959a3a27ce0a0615dda0a7

test:
  secret_key_base: 7f2fe0036995f077caffabf97839a4c56b05593c5d4262d7a1186deac08298e8106bb72c06f43010bb3bb44bd64cb98997b5176edc05c74fdac1cf9c2ca597d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 50174ba5b83b8c6867c785cd29f76c8198acc81880f72bff6ad82586d883fb1969e8afc62d8e1a58d81e5975589f78d7e620de16f8959a3a27ce0a0615dda0a7
